source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in api.gemspec.
gemspec

group :development do
  gem 'pg'
  gem 'byebug'
end

gem 'core', path: '../core'
