source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in core.gemspec.
gemspec

# To use a debugger
group :development, :test do
  gem 'pg'
  gem 'byebug'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
end
